// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (Users, error)
	GetUserByEmail(ctx context.Context, email string) (Users, error)
	GetUserById(ctx context.Context, uid uuid.UUID) (Users, error)
	GetUserByoAuthToken(ctx context.Context, accesstoken sql.NullString) (Users, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (Users, error)
}

var _ Querier = (*Queries)(nil)
