// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: users.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO "users" (
        email,
        name,
        avatar,
        "accessToken"
    )
VALUES ($1, $2, $3, $4)
RETURNING uid, name, email, avatar, "accessToken", "createdAt", "updatedAt"
`

type CreateUserParams struct {
	Email       string         `json:"email"`
	Name        sql.NullString `json:"name"`
	Avatar      sql.NullString `json:"avatar"`
	AccessToken sql.NullString `json:"accessToken"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (Users, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Email,
		arg.Name,
		arg.Avatar,
		arg.AccessToken,
	)
	var i Users
	err := row.Scan(
		&i.Uid,
		&i.Name,
		&i.Email,
		&i.Avatar,
		&i.AccessToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT uid, name, email, avatar, "accessToken", "createdAt", "updatedAt"
FROM "users"
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (Users, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i Users
	err := row.Scan(
		&i.Uid,
		&i.Name,
		&i.Email,
		&i.Avatar,
		&i.AccessToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT uid, name, email, avatar, "accessToken", "createdAt", "updatedAt"
FROM "users"
WHERE uid = $1
LIMIT 1
`

func (q *Queries) GetUserById(ctx context.Context, uid uuid.UUID) (Users, error) {
	row := q.db.QueryRowContext(ctx, getUserById, uid)
	var i Users
	err := row.Scan(
		&i.Uid,
		&i.Name,
		&i.Email,
		&i.Avatar,
		&i.AccessToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByoAuthToken = `-- name: GetUserByoAuthToken :one
SELECT uid, name, email, avatar, "accessToken", "createdAt", "updatedAt"
FROM "users"
WHERE "accessToken" = $1
LIMIT 1
`

func (q *Queries) GetUserByoAuthToken(ctx context.Context, accesstoken sql.NullString) (Users, error) {
	row := q.db.QueryRowContext(ctx, getUserByoAuthToken, accesstoken)
	var i Users
	err := row.Scan(
		&i.Uid,
		&i.Name,
		&i.Email,
		&i.Avatar,
		&i.AccessToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE "users"
SET email = $2,
    name = $3,
    avatar = $4,
    "accessToken" = $5,
    "updatedAt" = now()
WHERE uid = $1
RETURNING uid, name, email, avatar, "accessToken", "createdAt", "updatedAt"
`

type UpdateUserParams struct {
	Uid         uuid.UUID      `json:"uid"`
	Email       string         `json:"email"`
	Name        sql.NullString `json:"name"`
	Avatar      sql.NullString `json:"avatar"`
	AccessToken sql.NullString `json:"accessToken"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (Users, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.Uid,
		arg.Email,
		arg.Name,
		arg.Avatar,
		arg.AccessToken,
	)
	var i Users
	err := row.Scan(
		&i.Uid,
		&i.Name,
		&i.Email,
		&i.Avatar,
		&i.AccessToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
